version: '3.9'
services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - DB=mongodb+srv://user:1234567890@cluster0.ecduv.mongodb.net/test
        ports:
            - '5000:5000'
